### ISSUE TITLE
what is C:/sta.jpg?

### ISSUE THREAD

**Issue by znsoft** [arminkz/ShaderToy.NET#2]
https://github.com/arminkz/ShaderToy.NET/blob/4b992f691f5f758f9313b37b782e3004d2fb768a/ShaderToy.NET/MainWindow.xaml.cs#L94

> Ch0Image = new BitmapImage(new Uri(@"C:/sta.jpg"));

**Comment by arminkz** [comment]
it is hard coded path to a image i used to test the texture functionality it can be removed from source code now. because texture are loaded using open file dialog. 

i'll fix it soon thanks for mentioning this problem 👍
